### PR TITLE
Switch to a sublime-syntax based syntax definition.

### PR DESCRIPTION
**Pull request by willstott101**
This is work I've been doing at https://github.com/willstott101/django-sublime-syntax

I've deliberately not changed the colour of most built-in template tags as I don't think it adds to readability. I coloured most template tags as function calls, rather than keywords, as html tags are coloured like keywords so I found it hard to differentiate.

Before:
Screenshot from 2019-12-06 12-33-34

After:
Screenshot from 2019-12-06 12-29-55

### CODE REVIEW

**Comment by willstott101** [comment]
You'll have to enable github actions to get the tests, but they're passing on my fork

**Comment by squ1b3r** [comment]
@willstott101 Thanks a ton for your contribution and all the work. Going to review this over the weekend.

**Comment by squ1b3r** [comment]
@willstott101  Been busy this week so it will take a little longer, sorry. I also am thinking about making a separate branch for this so that I can merge and test, and then remove old syntax file and to avoid these changes getting to people before it's ready. Thoughts?

**Comment by willstott101** [comment]
I would be happy for this to merged into a separate branch if you would like to add to you it yourself. I could also give you commit access to my fork if you'd like to keep the single PR with it's diff intact.

**Comment by squ1b3r** [comment]
Created `syntax-refactoring` branch for these changes.

**Comment by willstott101** [comment]
I've moved the PR to that branch

**Pull request merged**
