### PR TITLE
Adds aurl tag

### PR DESCRIPTION
**Pull request by scuml**
Updates the README and adds an aurl convenience snippet - which outputs:
`<a href="{% url '{$0}' %}">$1</a>`

### CODE REVIEW

**Review by squ1b3r — APPROVED** [review]

**Comment by squ1b3r** [comment]
@scuml Thanks for all your contributions!

**Comment by squ1b3r** [comment]
@scuml Since you already initiated work related to fields would you mind adding model fields that are still missing? From just a quick overview I'd say we are at least missing `PositiveBigIntegerField` and `JSONField`

**Comment by scuml** [comment]
All missing fields, including `PositiveBigIntegerField` and `JSONField`, have already been merged in with #129 
https://github.com/squ1b3r/Djaneiro/pull/129/files

**Comment by scuml** [comment]
Could you merge this in?  Looks like it was just closed without being merged.

**Comment by squ1b3r** [comment]
Ah, right, but we are still missing them in the Readme.

**Comment by scuml** [comment]
That's what this branch was for :)

**Comment by scuml** [comment]
(There's a README update included with this)

**Comment by squ1b3r** [comment]
I don't see `PositiveBigIntegerField` and `JSONField` in there though. And now when it's merged the README in `main` still doesn't have those.

**Comment by scuml** [comment]
https://github.com/squ1b3r/Djaneiro/blob/master/Models/Model%20Fields/PositiveBigIntegerField%20(m_posbigint).sublime-snippet
https://github.com/squ1b3r/Djaneiro/blob/master/Models/Model%20Fields/JSONField%20(m_json).sublime-snippet

**Comment by scuml** [comment]
Oh I see - missing in the README

**Pull request closed without merging**
