### PR TITLE
Change search_fields attribute snippet code from list to tuple

### PR DESCRIPTION
**Pull request by mazulo**

### CODE REVIEW

**Comment by squ1b3r** [comment]
Thanks.

**Comment by mazulo** [comment]
It's my pleasure. Tuple rocks! Hahaha

**Comment by squ1b3r** [comment]
Heh, depends also keep in mind that Django recently started changing many of such variable to be lists bu default, so we might end up changing it all back one day :)

**Comment by mazulo** [comment]
Hum, interesting. I'll keep an eye about that

**Pull request merged**
