### PR TITLE
Comment/Uncomment commands now work in django templates

### LINKED ISSUE #10: Commenting on Django Templates incorrect
When the shortcut for commenting is pressed (Command - / ), comments are presented as standard HTML, rather than Django templates (as with the TextMate bundle).

### PR DESCRIPTION
**Pull request by scuml**
Comment/Uncomment command and hotkeys now work in django templates.

Before the comment key would place invalid comment syntax around text...

```
{# line 1
line 2 #}
```

Now the comment command detects if one or multiple lines are selected and intelligently chooses the best comment style:

```
{# line 1 #} 

{% comment %}
line 1
line 2
{% endcomment %}
```

Resolves #10

### CODE REVIEW

**Comment by scuml** [comment]
Don't merge yet - found some problems with the key mapping.

**Comment by scuml** [comment]
@squ1b3r How does this look?

**Comment by squ1b3r** [comment]
@scuml I haven't looked through it fully yet. Still need to finish reviewing that Python code. I'll try an find some time later this week.

**Review by squ1b3r — CHANGES_REQUESTED** [review]
Overall looks good. I don't have enough context to properly review all that python code, so I trust that it's correct.

**Pull request merged**
